<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>gauge.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="gauge.ico" />
    <Content Include="Resources\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Library\MicroGauge.Wpf\MicroGauge.Wpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Properties.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Properties.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
